prepares for venv installment on target platform

diff --git a/bin/debinsight b/bin/debinsight
--- a/bin/debinsight
+++ b/bin/debinsight
@@ -10,5 +10,21 @@
 # (C) Copyright 2019, Oliver Maurhart, dyle71@gmail.com
 # ------------------------------------------------------------
 
-/usr/bin/env python3 -m debinsight $*
+SCRIPT_LOCATION=`readlink -f $0`
+ROOT_FOLDER=`dirname $SCRIPT_LOCATION`
+ROOT_FOLDER=`dirname $ROOT_FOLDER`
+
+# Detect virtual env python3
+# ... installed on target system
+PYTHON3="$ROOT_FOLDER/bin/python3"
+if [ ! -x $PYTHON3 ]; then
+    # ... while under development
+    PYTHON3="$ROOT_FOLDER/venv/bin/python3"
+fi
+if [ ! -x $PYTHON3 ]; then
+    echo "Cannot find venv python3."
+    exit 1
+fi
+
+$PYTHON3 -m debinsight $*
 
